services:
  redis:
    image: redis:7-alpine
    container_name: catdog-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: [ "redis-server", "--appendonly", "yes" ]

  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: akp1n/catdog-api:latest
    ports:
      - "8001:8000"
    command: ["./entrypoint.sh"]

volumes:
  redis_data: